version: '3.7'
services:
  php_base:
    container_name: php_base
    build:
      context: ./docker/php/base
    image: php_base
    networks:
      - app-network

  proxy:
    container_name: proxy
    image: proxy
    build:
      context: ./docker/proxy
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - app-network

  sf_video_chat_api:
    container_name: sf_video_chat_api
    image: sf_video_chat_api
    build:
      context: ./docker/php/sf-video-chat-api
      dockerfile: Dockerfile
    volumes:
      - ./sf-video-chat-api/:/var/www/html
    depends_on:
      - mariadb
    networks:
      - app-network

  node_base:
    container_name: node_base
    build:
        context: ./docker/node/base
    image: node_base
    networks:
      - app-network

  nuxt_video_chat_front:
    restart: always
    container_name: nuxt_video_chat_front
    image: nuxt_video_chat_front
    build:
      context: ./docker/node/nuxt-video-chat-front
      dockerfile: Dockerfile
    volumes:
      - ./nuxt-video-chat-front/:/home/node/nuxt-video-chat-front
    extra_hosts:
      - api.video-chat.pl:172.17.0.1
    networks:
      - app-network
    ports:
      - 5000:5000
      - 3000:3000

  mariadb:
    container_name: sf_video_chat_mariadb
    image: mariadb:10.7.3-focal
    environment:
      MARIADB_ROOT_PASSWORD: pass1234
    volumes:
      - mariadb-database:/var/lib/mysql:rw
    ports:
      - 3307:3306
    networks:
      - app-network

  adminer:
    container_name: sf_video_chat_adminer
    image: adminer:4.8.1-standalone
    ports:
      - 9000:8080
    networks:
      - app-network

volumes:
  mariadb-database:

networks:
  app-network:
    driver: bridge