framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []
        mapping:
            paths:
                #UserAccess
                - '%kernel.project_dir%/src/Core/UserAuth/Infrastructure/Validator/Symfony/Mappings/RegisterUserCommand.yml'

                #Chat
                - '%kernel.project_dir%/src/Core/Chat/Infrastructure/Validator/Symfony/Mappings/FetchChatMessagesByIdQuery.yaml'
                - '%kernel.project_dir%/src/Core/Chat/Infrastructure/Validator/Symfony/Mappings/AddMessageHandlerCommand.yaml'

when@test:
    framework:
        validation:
            not_compromised_password: false
